version: '3.8'

services:
  remote_control_server:
    container_name: remote_control_server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=1234
      - DB_NAME=postgres
    ports:
      - 8080:8080
    depends_on:
      - postgres_db
      # - timescale_db

  postgres_db:
    container_name: postgres_db
    image: postgres:13
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=user
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  # timescale_db:
  #   container_name: timescale_db
  #   image: timescale/timescaledb:latest-pg13
  #   restart: always
  #   env_file:
  #     - .env
  #   environment:
  #     - POSTGRES_PASSWORD=1234
  #     - POSTGRES_USER=user
  #     - POSTGRES_DB=timescale
  #   volumes:
  #     - timescale_data:/var/lib/postgresql/data/
  #   ports:
  #     - 5434:5434

volumes:
  postgres_data:
  # timescale_data:
