version: '3.8'

services:
  remote_control_server:
    container_name: remote_control_server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}

      - GOMAXPROCS=7 # Set the number of CPU cores for the Go application

    deploy:
      resources:
        limits:
          cpus: '7.0' # Maximum 2 CPU cores for the Go server
          memory: '6g' # Maximum 4GB of memory for the Go server
        reservations:
          cpus: '7.0' # Reserve at least 1 CPU core for the Go server
          memory: '6g' # Reserve at least 2GB of memory for the Go server
    ports:
      - 8080:8080
    depends_on:
      - influxdb
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13
    restart: always
    command: postgres -c 'max_connections=20000'
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
    deploy:
      resources:
        limits:
          cpus: '3.5'
          memory: '4g'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432

  influxdb:
    container_name: influxdb
    image: influxdb:latest
    restart: always
    env_file:
      - .env
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    volumes:
      - influxdb_data:/var/lib/influxdb
      - ./init-influxdb.sh:/init-influxdb.sh
    ports:
      - 8086:8086

volumes:
  postgres_data:
  influxdb_data:
